# For more information: https://laravel.com/docs/sail
version: "3.5"
services:
  laravel.test:
    container_name: "wend_app"
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          WWWGROUP: "${WWWGROUP:-1000}"
    image: laravel/docker
    volumes:
      - "./start-container:/usr/local/bin/start-container"
      - "app_volume:/var/www/html"
    ports:
      - "${APP_HTTP_PORT:-8000}:8000"
    networks:
      - "my_network"
networks:
  my_network:
    driver: bridge
volumes:
  app_volume:
    driver: local