# For more information: https://laravel.com/docs/sail
version: "3.5"
services:
  laravel.test:
    container_name: "wend_app"
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          WWWGROUP: "${WWWGROUP:-1000}"
          WWWUSER: "${WWWUSER:-sail}"
          GIT_REPOSITORY: "${GIT_REPOSITORY}"
          GIT_BRANCH: "${GIT_BRANCH:-master}"
    image: wend/laravel
    environment:
      GIT_UPDATE: "1"
    volumes:
      - "./start-container:/usr/local/bin/start-container"
      - "app_volume:/var/www/html"
    ports:
      - "${APP_HTTP_PORT:-8000}:8000"
    secrets:
      - id_rsa
    networks:
      - "my_network"
networks:
  my_network:
    driver: bridge
volumes:
  app_volume:
    driver: local
secrets:
  id_rsa:
    file: ./id_rsa_shared 